{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "from dotenv import load_dotenv\n",
    "\n",
    "load_dotenv()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "ename": "ImportError",
     "evalue": "libffi.so.7: cannot open shared object file: No such file or directory",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mImportError\u001b[0m                               Traceback (most recent call last)",
      "\u001b[0;31mImportError\u001b[0m: libffi.so.7: cannot open shared object file: No such file or directory"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "thread '<unnamed>' panicked at 'Python API call failed', /github/home/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pyo3-0.15.2/src/err/mod.rs:582:5\n"
     ]
    },
    {
     "ename": "PanicException",
     "evalue": "Python API call failed",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mPanicException\u001b[0m                            Traceback (most recent call last)",
      "\u001b[1;32m/home/anurag/MY/anurag/Projects/BotaniScan-api/notebooks/githubTesting.ipynb Cell 1\u001b[0m line \u001b[0;36m1\n\u001b[0;32m----> <a href='vscode-notebook-cell:/home/anurag/MY/anurag/Projects/BotaniScan-api/notebooks/githubTesting.ipynb#W0sZmlsZQ%3D%3D?line=0'>1</a>\u001b[0m \u001b[39mfrom\u001b[39;00m \u001b[39mgithub\u001b[39;00m \u001b[39mimport\u001b[39;00m Github\n\u001b[1;32m      <a href='vscode-notebook-cell:/home/anurag/MY/anurag/Projects/BotaniScan-api/notebooks/githubTesting.ipynb#W0sZmlsZQ%3D%3D?line=2'>3</a>\u001b[0m \u001b[39mfrom\u001b[39;00m \u001b[39mgithub\u001b[39;00m \u001b[39mimport\u001b[39;00m Auth\n\u001b[1;32m      <a href='vscode-notebook-cell:/home/anurag/MY/anurag/Projects/BotaniScan-api/notebooks/githubTesting.ipynb#W0sZmlsZQ%3D%3D?line=4'>5</a>\u001b[0m auth \u001b[39m=\u001b[39m Auth\u001b[39m.\u001b[39mToken(\u001b[39m'\u001b[39m\u001b[39m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\u001b[39m\u001b[39m'\u001b[39m)\n",
      "File \u001b[0;32m~/anaconda3/envs/ai/lib/python3.8/site-packages/github/__init__.py:58\u001b[0m\n\u001b[1;32m     37\u001b[0m __all__ \u001b[39m=\u001b[39m [\n\u001b[1;32m     38\u001b[0m     \u001b[39m\"\u001b[39m\u001b[39mAuth\u001b[39m\u001b[39m\"\u001b[39m,\n\u001b[1;32m     39\u001b[0m     \u001b[39m\"\u001b[39m\u001b[39mAppAuthentication\u001b[39m\u001b[39m\"\u001b[39m,\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m     53\u001b[0m     \u001b[39m\"\u001b[39m\u001b[39mUnknownObjectException\u001b[39m\u001b[39m\"\u001b[39m,\n\u001b[1;32m     54\u001b[0m ]\n\u001b[1;32m     56\u001b[0m \u001b[39mimport\u001b[39;00m \u001b[39mlogging\u001b[39;00m\n\u001b[0;32m---> 58\u001b[0m \u001b[39mfrom\u001b[39;00m \u001b[39mgithub\u001b[39;00m \u001b[39mimport\u001b[39;00m Auth\n\u001b[1;32m     59\u001b[0m \u001b[39mfrom\u001b[39;00m \u001b[39mgithub\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mAppAuthentication\u001b[39;00m \u001b[39mimport\u001b[39;00m AppAuthentication\n\u001b[1;32m     60\u001b[0m \u001b[39mfrom\u001b[39;00m \u001b[39mgithub\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mGithubIntegration\u001b[39;00m \u001b[39mimport\u001b[39;00m GithubIntegration\n",
      "File \u001b[0;32m~/anaconda3/envs/ai/lib/python3.8/site-packages/github/Auth.py:29\u001b[0m\n\u001b[1;32m     26\u001b[0m \u001b[39mfrom\u001b[39;00m \u001b[39mdatetime\u001b[39;00m \u001b[39mimport\u001b[39;00m datetime, timedelta, timezone\n\u001b[1;32m     27\u001b[0m \u001b[39mfrom\u001b[39;00m \u001b[39mtyping\u001b[39;00m \u001b[39mimport\u001b[39;00m Dict, Optional, Union\n\u001b[0;32m---> 29\u001b[0m \u001b[39mimport\u001b[39;00m \u001b[39mjwt\u001b[39;00m\n\u001b[1;32m     31\u001b[0m \u001b[39mfrom\u001b[39;00m \u001b[39mgithub\u001b[39;00m \u001b[39mimport\u001b[39;00m Consts\n\u001b[1;32m     32\u001b[0m \u001b[39mfrom\u001b[39;00m \u001b[39mgithub\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mInstallationAuthorization\u001b[39;00m \u001b[39mimport\u001b[39;00m InstallationAuthorization\n",
      "File \u001b[0;32m~/anaconda3/envs/ai/lib/python3.8/site-packages/jwt/__init__.py:1\u001b[0m\n\u001b[0;32m----> 1\u001b[0m \u001b[39mfrom\u001b[39;00m \u001b[39m.\u001b[39;00m\u001b[39mapi_jwk\u001b[39;00m \u001b[39mimport\u001b[39;00m PyJWK, PyJWKSet\n\u001b[1;32m      2\u001b[0m \u001b[39mfrom\u001b[39;00m \u001b[39m.\u001b[39;00m\u001b[39mapi_jws\u001b[39;00m \u001b[39mimport\u001b[39;00m (\n\u001b[1;32m      3\u001b[0m     PyJWS,\n\u001b[1;32m      4\u001b[0m     get_unverified_header,\n\u001b[1;32m      5\u001b[0m     register_algorithm,\n\u001b[1;32m      6\u001b[0m     unregister_algorithm,\n\u001b[1;32m      7\u001b[0m )\n\u001b[1;32m      8\u001b[0m \u001b[39mfrom\u001b[39;00m \u001b[39m.\u001b[39;00m\u001b[39mapi_jwt\u001b[39;00m \u001b[39mimport\u001b[39;00m PyJWT, decode, encode\n",
      "File \u001b[0;32m~/anaconda3/envs/ai/lib/python3.8/site-packages/jwt/api_jwk.py:3\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[39mimport\u001b[39;00m \u001b[39mjson\u001b[39;00m\n\u001b[0;32m----> 3\u001b[0m \u001b[39mfrom\u001b[39;00m \u001b[39m.\u001b[39;00m\u001b[39malgorithms\u001b[39;00m \u001b[39mimport\u001b[39;00m get_default_algorithms\n\u001b[1;32m      4\u001b[0m \u001b[39mfrom\u001b[39;00m \u001b[39m.\u001b[39;00m\u001b[39mexceptions\u001b[39;00m \u001b[39mimport\u001b[39;00m InvalidKeyError, PyJWKError, PyJWKSetError\n\u001b[1;32m      7\u001b[0m \u001b[39mclass\u001b[39;00m \u001b[39mPyJWK\u001b[39;00m:\n",
      "File \u001b[0;32m~/anaconda3/envs/ai/lib/python3.8/site-packages/jwt/algorithms.py:6\u001b[0m\n\u001b[1;32m      3\u001b[0m \u001b[39mimport\u001b[39;00m \u001b[39mjson\u001b[39;00m\n\u001b[1;32m      5\u001b[0m \u001b[39mfrom\u001b[39;00m \u001b[39m.\u001b[39;00m\u001b[39mexceptions\u001b[39;00m \u001b[39mimport\u001b[39;00m InvalidKeyError\n\u001b[0;32m----> 6\u001b[0m \u001b[39mfrom\u001b[39;00m \u001b[39m.\u001b[39;00m\u001b[39mutils\u001b[39;00m \u001b[39mimport\u001b[39;00m (\n\u001b[1;32m      7\u001b[0m     base64url_decode,\n\u001b[1;32m      8\u001b[0m     base64url_encode,\n\u001b[1;32m      9\u001b[0m     der_to_raw_signature,\n\u001b[1;32m     10\u001b[0m     force_bytes,\n\u001b[1;32m     11\u001b[0m     from_base64url_uint,\n\u001b[1;32m     12\u001b[0m     is_pem_format,\n\u001b[1;32m     13\u001b[0m     is_ssh_key,\n\u001b[1;32m     14\u001b[0m     raw_to_der_signature,\n\u001b[1;32m     15\u001b[0m     to_base64url_uint,\n\u001b[1;32m     16\u001b[0m )\n\u001b[1;32m     18\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[1;32m     19\u001b[0m     \u001b[39mimport\u001b[39;00m \u001b[39mcryptography\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mexceptions\u001b[39;00m\n",
      "File \u001b[0;32m~/anaconda3/envs/ai/lib/python3.8/site-packages/jwt/utils.py:7\u001b[0m\n\u001b[1;32m      4\u001b[0m \u001b[39mfrom\u001b[39;00m \u001b[39mtyping\u001b[39;00m \u001b[39mimport\u001b[39;00m Any, Union\n\u001b[1;32m      6\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[0;32m----> 7\u001b[0m     \u001b[39mfrom\u001b[39;00m \u001b[39mcryptography\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mhazmat\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mprimitives\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39masymmetric\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mec\u001b[39;00m \u001b[39mimport\u001b[39;00m EllipticCurve\n\u001b[1;32m      8\u001b[0m     \u001b[39mfrom\u001b[39;00m \u001b[39mcryptography\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mhazmat\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mprimitives\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39masymmetric\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mutils\u001b[39;00m \u001b[39mimport\u001b[39;00m (\n\u001b[1;32m      9\u001b[0m         decode_dss_signature,\n\u001b[1;32m     10\u001b[0m         encode_dss_signature,\n\u001b[1;32m     11\u001b[0m     )\n\u001b[1;32m     12\u001b[0m \u001b[39mexcept\u001b[39;00m \u001b[39mModuleNotFoundError\u001b[39;00m:\n",
      "File \u001b[0;32m~/anaconda3/envs/ai/lib/python3.8/site-packages/cryptography/hazmat/primitives/asymmetric/ec.py:10\u001b[0m\n\u001b[1;32m      7\u001b[0m \u001b[39mimport\u001b[39;00m \u001b[39mtyping\u001b[39;00m\n\u001b[1;32m      9\u001b[0m \u001b[39mfrom\u001b[39;00m \u001b[39mcryptography\u001b[39;00m \u001b[39mimport\u001b[39;00m utils\n\u001b[0;32m---> 10\u001b[0m \u001b[39mfrom\u001b[39;00m \u001b[39mcryptography\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mhazmat\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39m_oid\u001b[39;00m \u001b[39mimport\u001b[39;00m ObjectIdentifier\n\u001b[1;32m     11\u001b[0m \u001b[39mfrom\u001b[39;00m \u001b[39mcryptography\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mhazmat\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mprimitives\u001b[39;00m \u001b[39mimport\u001b[39;00m _serialization, hashes\n\u001b[1;32m     12\u001b[0m \u001b[39mfrom\u001b[39;00m \u001b[39mcryptography\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mhazmat\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mprimitives\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39masymmetric\u001b[39;00m \u001b[39mimport\u001b[39;00m utils \u001b[39mas\u001b[39;00m asym_utils\n",
      "File \u001b[0;32m~/anaconda3/envs/ai/lib/python3.8/site-packages/cryptography/hazmat/_oid.py:7\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[39m# This file is dual licensed under the terms of the Apache License, Version\u001b[39;00m\n\u001b[1;32m      2\u001b[0m \u001b[39m# 2.0, and the BSD License. See the LICENSE file in the root of this repository\u001b[39;00m\n\u001b[1;32m      3\u001b[0m \u001b[39m# for complete details.\u001b[39;00m\n\u001b[1;32m      5\u001b[0m \u001b[39mimport\u001b[39;00m \u001b[39mtyping\u001b[39;00m\n\u001b[0;32m----> 7\u001b[0m \u001b[39mfrom\u001b[39;00m \u001b[39mcryptography\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mhazmat\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mbindings\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39m_rust\u001b[39;00m \u001b[39mimport\u001b[39;00m (\n\u001b[1;32m      8\u001b[0m     ObjectIdentifier \u001b[39mas\u001b[39;00m ObjectIdentifier,\n\u001b[1;32m      9\u001b[0m )\n\u001b[1;32m     10\u001b[0m \u001b[39mfrom\u001b[39;00m \u001b[39mcryptography\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mhazmat\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mprimitives\u001b[39;00m \u001b[39mimport\u001b[39;00m hashes\n\u001b[1;32m     13\u001b[0m \u001b[39mclass\u001b[39;00m \u001b[39mExtensionOID\u001b[39;00m:\n",
      "\u001b[0;31mPanicException\u001b[0m: Python API call failed"
     ]
    }
   ],
   "source": [
    "from github import Github\n",
    "\n",
    "from github import Auth\n",
    "\n",
    "auth = Auth.Token('acess tocken')\n",
    "\n",
    "g = Github(auth=auth)\n",
    "\n",
    "repo = g.get_repo(\"anurag629/BotaniScan-API\")\n",
    "\n",
    "print(repo.stargazers_count)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "ai",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.0"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
